services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - /home/taz/Documents/full_project/prometheus_exporters/prometheus:/etc/prometheus
    networks:
      - localprom
  node-exporter:
    image: prom/node-exporter
    networks:
      - localprom
    ports:
      - 9100:9100
  grafana:
    image: grafana/grafana
    ports: 
      - 3000:3000
    volumes: 
      - /home/taz/mnt/NAS/logging/grafana-data:/var/lib/grafana
      - /home/taz/Documents/full_project/prometheus_exporters/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - /home/taz/Documents/full_project/prometheus_exporters/grafana.dashboard.json:/var/lib/grafana/dashboards/dashboard.json
      - /home/taz/Documents/full_project/prometheus_exporters/grafana/default.yaml:/etc/grafana/provisioning/dashboards/default.yaml
    networks:
      - localprom

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor
    volumes: 
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices: 
      - dev/kmsg
    ports:
      - 8080:8080
    networks:
      - localprom

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

  
networks:
  localprom:
    driver: bridge

volumes:
  grafana-data:
    