services:
  shairport-sync:
    image: mikebrady/shairport-sync:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - ./volumes/shairport-sync/shairport-sync.conf:/etc/shairport-sync.conf
    devices:
      - /dev/snd:/dev/snd   
    environment:
      - SHARED_SECRET=secret
      - AIRPLAY_NAME=AirPlay
      - AIRPLAY_PORT=5000
      - AIRPLAY_PASSWORD=password
      - AIRPLAY_VOLUME=100
      - AIRPLAY_VOLUME_STEP=5
      - AIRPLAY_VOLUME_MIN=0
      - AIRPLAY_VOLUME_MAX=100
      - AIRPLAY_VOLUME_DEFAULT=50
    logging:
      options:
        max-size: "200k"
        max-file: "10"