services:
  shairport-sync:
    image: mikebrady/shairport-sync:latest
    network_mode: host
    restart: unless-stopped
    devices:
      - /dev/snd
    logging:
      options:
        max-size: "200k"
        max-file: "10"